ministryofjustice/bichard7-next-shared-infrastructure

terraform/shared_account_sandbox_infra_ci/iam.tf
Allows the sandbox nuke role to pull assets from the shared account  s3 bucket
=> chore: 🤖 allow nuke role in sandboxes to pull from shared s3

terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
Adds the codebuild job to the path to live pipeline, so it runs just before the manual approval step.
=> feat: 🎸 generate diff urls & output to slack before prod deploy

ansible/vars/users.yml
A waiver has been issued for engineers with a pending SC application, and these users should be able to access the production environment
=> Allow users with pending clearance access to prod

ansible/remove_users.yml, ansible/vars/users.yml, terraform/shared_account_pathtolive_bootstrap/README.md, terraform/shared_account_pathtolive_infra/README.md, terraform/shared_account_pathtolive_infra_ci/README.md, terraform/shared_account_pathtolive_infra_ci_monitoring/README.md, terraform/shared_account_sandbox_bootstrap/README.md, terraform/shared_account_sandbox_infra/README.md, terraform/shared_account_sandbox_infra_ci/README.md
Ansible started throwing fatal errors when a deleted user's ssm could not be found. We can safely ignore these errors because most of the time we expect them to be deleted.
Also:
- delete Tolu
- remove Joe from non_sc user group
=> fix: 🐛 ignore resource not found for deleted users

terraform/modules/shared_cd_common_jobs/build_core.tf, terraform/modules/shared_cd_common_jobs/build_ui.tf, terraform/modules/shared_cd_common_jobs/vars.tf, terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf, terraform/shared_account_sandbox_infra_ci/main.tf
- codebuild job to build the ui docker image watches github for pushes to main and builds the semaphore
- watch for semaphore changes and trigger a pipeline release on change
- pass the ui image hash through the pipeline line so can be picked up by "code to be deployed" slack bot
- Refactor core codebuild job to run as container (code was copied from the reporting codebuild job)
Will only merge once the ecr repo is already deployed to prod
=> feat: 🎸 add bichard7-next-ui to pipeline & build codebuild job

terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
The deploy step in the pipeline is failing because it is trying to access a variable that isn't being passed through yet.
=> fix: 🐛 UI var preventing deploy

terraform/shared_account_pathtolive_infra_ci_monitoring/README.md, terraform/shared_account_pathtolive_infra_ci_monitoring/data.tf, terraform/shared_account_pathtolive_infra_ci_monitoring/ecr_alarms.tf, terraform/shared_account_pathtolive_infra_ci_monitoring/lambda_slack_webhook.tf, terraform/shared_account_pathtolive_infra_ci_monitoring/policies/allow_lambda_query.json, terraform/shared_account_pathtolive_infra_ci_monitoring/source/query_num_of_repo_images.py.tpl
This creates:
- a new slack lambda in the parent ptl account
- cloudwatch alarm that triggers if there are no image in the ecr repo
I went with this method as it was simplier than the keeping all the alarms in the child account, doing that would mean fiddling around with lots of cross account permissions for each repo and for the cloudwatch alarm lambda too.
=> feat: 🎸 add slack lambda & ecr alarm when no images in repo

terraform/modules/shared_cd_common_jobs/build_ui.tf, terraform/modules/shared_cd_common_jobs/outputs.tf, terraform/shared_account_pathtolive_infra_ci/main.tf
ui hash wasn't updating because the correct env vars weren't being passed to it when the image was being built, this passes the IS_CD env vars to the ui codebuild job so will now update the semaphores.
=> fix: 🐛 ui was not updating semaphores; didn't have cd env vars

terraform/shared_account_sandbox_infra_ci/locals.tf
Delete sandbox b nuke temporarily to avoid deletion of resources deployed to sandbox b.
=> Delete sandbox b nuke resources temporarily

terraform/shared_account_sandbox_infra_ci/locals.tf
This PR re enables the Sandbox B nuke codebuild job.
This reverts commit c38951032d6eb996362a456579afc01132788cb3.
=> Revert "Delete sandbox b nuke resources temporarily (#87)"

.pre-commit-config.yaml, terraform/shared_account_pathtolive_infra/README.md, terraform/shared_account_pathtolive_infra_ci/README.md, terraform/shared_account_pathtolive_infra_ci/build_production.tf, terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf, terraform/shared_account_pathtolive_infra_ci_monitoring/README.md, terraform/shared_account_sandbox_infra/README.md, terraform/shared_account_sandbox_infra_ci/README.md
* import the `INFRA_MODULES_COMMIT_HASH` to e2e, preprod and production
The same commit hash is passed to each stage because it is exported into the "HASHES" namespace (see below pr)
This var is exported in this [PR](https://github.com/ministryofjustice/bichard7-next-infrastructure/pull/964)
=> ci: 🎡 import infra modules param to code build deploy steps

terraform/shared_account_pathtolive_infra_ci/iam.tf
This PR updates `Bichard7-CI-Access` role to allow the CI user to tag and untag the MWAA environment
=> Update Bichard7-CI-Access role to tag and untag MWAA environment

terraform/modules/shared_cd_common_jobs/build_core.tf
This has been failing because it's been running out of memory, but succeeds with the increased container size
=> Bump container size for core build

terraform/shared_account_pathtolive_infra_ci/e2e_tests.tf, terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
This PR sets up a codebuild job in the deploy pipeline, to run after the e2e tests have finished, which generates more production-like data.
See also https://github.com/ministryofjustice/bichard7-next-ui/pull/174
=> Seed the e2e environment with generated data

terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf, terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live_iam.tf
The UI repo has been added as a codestar github connection, and the repository is used as an input to the `seed-e2e-data` step
=> Fix input artifacts to `seed-e2e-data` pipeline stage

terraform/shared_account_pathtolive_infra_ci/build_e2e_test_environments.tf, terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
This deploys the codebuild job but leaves the pipeline steps commented for now to avoid blocking things
=> Deploy conductor JSON definitions as a step in the pipeline

terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
Add verify e2e test ecs services to the pipeline and fix the run order of actions.
=> Add verify e2e test ecs services to the pipeline

terraform/modules/codebuild_monitoring/db.tf
Our Grafan database engine version in shared account has been upgraded (automatically) to 13.8.
This PR updates the version in our terraform code to match our AWS environment.
=> Upgrade Grafana db engine version in path to live to 13.8

terraform/shared_account_pathtolive_infra_ci/e2e_tests.tf
The `seed-e2e-data` job was failing to install standing data for b7 core dependency due to lack of memory. This PR fixes the issue.
=> Increase seed-e2e-data cb job memory

ansible/vars/users.yml
There is uncertainty if designers need access to AWS, I'm just removing Miles for now and can revisit if there is a need later on down the line
=> Removed miles from AWS

applyci-access.yml, applyci-buildspec.yml, applyci-monitoring.yml, manage-users-buildspec.yml, terraform/modules/shared_cd_common_jobs/cd_layer.tf, terraform/modules/shared_cd_common_jobs/manage_aws_users.tf, terraform/shared_account_pathtolive_infra_ci/ci_monitoring.tf
This PR updates the below CodeBuild jobs to use the `ci-admin` user instead of the default `ci` user. Previously, these jobs used the default `ci` user and attached the admin group to be able to apply the Terraform changes. However, given that other CodeBuild jobs shared the same ci user, all jobs had admin access during the execution of these specific jobs, causing security issues. Additionally, these jobs were random failing because attaching the admin group to a user could take some time, leading to instances where the admin group was not applied to the user on time.
Codebuild jobs updated:
- `apply-ci-monitoring-layer`
- `apply-codebuild-layer`
- `manage-aws-users`
=> Update specific codebuild jobs to use ci-admin user

terraform/shared_account_pathtolive_infra_ci_monitoring/ecr_alarms.tf
The lambda recurses through the repositories we have and initiates quite a few queries, which averages (by eye) around 4.4 seconds at the moment. Changing the timeout to 10 seconds will reduce alert noise for a bit, once it gets to 10s we should probably look at optimising the query.
=> Change timeout for ECR queries to 10s

ansible/vars/users.yml
This just cleans up the list of team members who have left Bichard
=> Removed redundant users in users.yml

terraform/shared_account_pathtolive_infra_ci/promotion_pipeline_path_to_live.tf
Our current pipeline separates the deploy and test phases, but this means that consecutive releases can end up adversely impacting eachother. This PR merges the three stages into one so that only one deploy and test can take place at a time. One added benefit is that as one release is actively deploying and testing, any subsequent releases will supersede eachother so there's less noise in the pipeline
=> Merge some of the pipeline stages because multiple releases were treading on eachothers' toes

terraform/modules/shared_cd_common_jobs/build_offline_binaries.tf
This PR changes the `trivy-scan-containers` codebuild to run daily instead of every Monday
=> Set cron job to run daily instead of every monday

terraform/shared_account_pathtolive_infra_ci/e2e_tests.tf
We run the E2E tests as part of our deployment pipeline so there's no value in running it when we merge into main. The CodeBuild job schedule is also unused.
Remove E2E tests CodeBuild job schedule and webhook.
=> Remove E2E tests CodeBuild job schedule and webhook

terraform/shared_account_pathtolive_infra_ci/build_uat_environment.tf
This PR adds a codebuild job to the shared account. It references the buildspec in `core/packages/uat-data`, and adds a cron trigger to run at 00:00, 08:00 and 14:00 daily. 
Each time it runs, it will upload 10 versions of each trigger UAT Bichard.
=> Firebreak: Add codebuild job to run UAT seed script

terraform/modules/codebuild_base_resources/locals.tf, terraform/modules/codebuild_base_resources/outputs.tf, terraform/modules/codebuild_base_resources/variables.tf, terraform/modules/codebuild_base_resources/vpc_codebuild_sgs.tf, terraform/shared_account_pathtolive_infra_ci/build_e2e_test_environments.tf, terraform/shared_account_pathtolive_infra_ci/build_load_test_environment.tf, terraform/shared_account_pathtolive_infra_ci/build_preprod.tf, terraform/shared_account_pathtolive_infra_ci/build_production.tf, terraform/shared_account_pathtolive_infra_ci/build_uat_environment.tf, terraform/shared_account_pathtolive_infra_ci/e2e_tests.tf, terraform/shared_account_pathtolive_infra_ci/main.tf, terraform/shared_account_pathtolive_infra_ci/outputs.tf
This PR implements separate security groups for each environment within the shared account. These security groups are assigned to CodeBuild jobs that require access to the corresponding environment’s resources via VPC peering.
Currently, a single security group is used for all CodeBuild jobs, allowing them to access all environments. By introducing distinct security groups, access can be restricted, ensuring each CodeBuild job only has the necessary permissions for its designated environment.
=> Update VPC configs for unique CodeBuild jobs by environment

terraform/shared_account_pathtolive_infra_ci/build_preprod.tf
PR to add VPC config for run preprod tests codebuild job. This allows accessing resource in preprod environment via VPC peering.
=> Add VPC config for run preprod tests job

terraform/shared_account_pathtolive_infra_ci/build_e2e_test_environments.tf, terraform/shared_account_pathtolive_infra_ci/build_preprod.tf, terraform/shared_account_pathtolive_infra_ci/data.tf, terraform/shared_account_pathtolive_infra_ci/e2e_tests.tf, terraform/shared_account_pathtolive_infra_ci/locals.tf
This PR updates the following Codebuild jobs to use Codebuild 2023 Base image:
- `deploy-integration-next-e2e-test`
- `destroy-integration-next-e2e-test`
- `run-e2e-test-migrations`
- `apply-dev-sgs-to-e2e-test`
- `remove-dev-sgs-from-e2e-test`
- `integration-test-preprod`
=> Update e2e test jobs to use Codebuild 2023 Base image

terraform/modules/shared_cd_common_jobs/build_conductor_image.tf
The image build for Conductor had been consistently failing, likely due to insufficient memory. To address this, we increased the compute resource size. We tested this with an override to use the new resource, and it has seemed to have resolved the failures and also reduced build times, making the trade-off in resource usage worthwhile.
=> Bump compute size for conductor image codebuild

terraform/modules/shared_cd_common_jobs/build_beanconnect.tf, terraform/modules/shared_cd_common_jobs/build_conductor_image.tf
We need to use the old amazon linux 2 image until we sort out the issue with Docker versions.
Amazon linux 2 is using v20.10.24 and Amazon linux 2023 is using v27.3.1
A [ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/BICAWS7/boards/1368/backlog?selectedIssue=BICAWS7-3673) has been created to sort this issue
=> Use amazon linux 2 for building Conductor and Beanconnect image
